### ISSUE TITLE
Name & position statements show over photo on mobile browser

### ISSUE THREAD

**Issue by zachmonteith** [wevote/WebApp#474] opened 2016-09-20 18:12 UTC
Since implementation of read more link truncation, alignment of candidate name, position, and position statement text is off, partially obscuring the candidate image. NOTE: We believe this issue is caused by transitioning a "p" (paragraph tag) to a "div" for the class "explicit-position__text" in:
/src/js/components/Widgets/PositionSupportOpposeSnippet.jsx and
/src/js/components/Widgets/PositionInformationOnlySnippet.jsx

![img_4323](https://cloud.githubusercontent.com/assets/17035647/18682946/12cff340-7f23-11e6-9759-d126e6069945.PNG)
![img_4324](https://cloud.githubusercontent.com/assets/17035647/18682947/12f434b2-7f23-11e6-8db6-c3f62b787e69.PNG)

**Comment by ixley** [comment] 2016-09-20 18:28
@zachmonteith is this live or only on the develop branch? I'm not able to reproduce this on the live site.

**Comment by zachmonteith** [comment] 2016-09-20 18:30
this is live on wevote.me, but only experienced the behavior on a mobile browser.

1) navigate to wevote.me in mobile browser (I used chrome on iPhone 5s)
2) search for "league of pissed off voters" (or really, "piss" will do the trick)
3) scroll down to candidates in their voter guide

**Comment by ixley** [comment] 2016-09-20 19:20
I still can't reproduce in mobile (iOS) Chrome or Safari. Maybe clear your
cache?

**Comment by zachmonteith** [comment] 2016-09-20 19:36
hmm, that didn't seem to fix it.  Specifically I am at url https://wevote.me/theleaguesf, my current address is set to San Francisco 94116 and I am looking at their Positions for Other Elections.  bug beings with Preston Picus (he is the fourth candidate I can see), also happens with Kamala Harris, Jackie Speier, Bernie Sanders, Jane Kim, and Victor Hwang.

**Comment by ixley** [comment] 2016-09-20 19:59
@zachmonteith I'll leave this to you to troubleshoot unless you can provide more info with what's happening to the layout (try emulating mobile in Chrome desktop and using the inspector). I did notice that there's an anchor tag wrapping `card-child__avatar` which should probably just be wrapping the image instead (`card-child__avatar` and `card-card__content` should be siblings), but I can't comment on whether that's causing the problem since I can't recreate it.

![img_8612](https://cloud.githubusercontent.com/assets/160662/18686596/4d6df5ac-7f31-11e6-8490-02e317bd6d18.PNG)

**Comment by ixley** [comment] 2016-09-23 06:24
@zachmonteith I'm going to close this for now. Reopen if you are able to reproduce on multiple devices and/or can provide more info.

**Comment by DaleMcGrew** [comment] 2016-09-23 13:56
I am still seeing it on my iPhone 6, Safari and Chrome, after clearing cache, as well as in incognito mode.

**Comment by ixley** [comment] 2016-09-23 15:22
😕 Strange. I'll see if I can check on other devices too. I have no idea what to attribute the difference to since I still can't reproduce on my end desktop or mobile, chrome or safari, local or live. Try fixing the tag wrapping issue I mentioned above to see if that does anything for you. If it doesn't, use an inspector to find out which specific elements are breaking layout.

**Comment by DaleMcGrew** [comment] 2016-09-24 20:20
Fixed!

**Closed by DaleMcGrew** 2016-09-24 20:20 UTC
Labels: Priority 1
