### ISSUE TITLE
Navigating to settings/account logs you out of the WebApp

### ISSUE THREAD

**Issue by SailingSteve** [wevote/WebApp#1606] opened 2018-07-13 22:06 UTC
There are slightly different symptoms in WebApp on local host, and in Cordova, but the problem is also
reproducible at https://wevote.us/settings/account

1) Start your WebApp
2) Login to Facebook (or Twitter)
3) Press the face icon in the upper right
4) Click Your Settings
5) Click Signin
6) Choose Facebook
(The redirect happens, and relies on prior cookies, and takes you back to /ballot -- you are logged in)
7) Click the Face Icon, then "Your Settings", then "Your Account"
Then you are shown the /account page, but your face icon goes to default, and both Signin buttons are displayed.  You've been signed out.

**Comment by SailingSteve** [comment] 2018-07-13 22:15
If as you go through those steps, if you are using the chrome debugger, on the network tab, and filtered to voterRetrieve

<img width="659" alt="screen shot 2018-07-13 at 3 07 21 pm" src="https://user-images.githubusercontent.com/6923653/42716086-b4c5ede6-86ae-11e8-80cc-9c666ae30303.png">

You will see 10 occurrences of voterRetrieve
On the 8th, you will see the facebook info come back

<img width="706" alt="screen shot 2018-07-13 at 3 10 42 pm" src="https://user-images.githubusercontent.com/6923653/42716153-04e77bbe-86af-11e8-9e1a-c9df8d594737.png">

On the 9th, you will see ...
<img width="672" alt="screen shot 2018-07-13 at 3 11 59 pm" src="https://user-images.githubusercontent.com/6923653/42716175-215d3e14-86af-11e8-9bef-579cb10ac2a0.png">

... a default Voter like full_name: "Voter-wv02voter127482"
Which also brings "false" to the signed_in_facebook field, which pollutes the VoterStore and logs you out.

**Comment by DaleMcGrew** [comment] 2018-07-17 16:55
I finally found a solution to this, and the fix is on the live server. Please let me know if you find anything still broken. Thank you @SailingSteve for your thorough documentation of the issue.

**Comment by SailingSteve** [comment] 2018-07-17 22:21
@DaleMcGrew Which PR fixed the problem?

**Comment by DaleMcGrew** [comment] 2018-07-17 22:23
The biggest change was in this PR: https://github.com/wevote/WeVoteServer/pull/857/files

**Comment by DaleMcGrew** [comment] 2018-07-26 01:41
I fixed this for Facebook, but alas the problem still exists for Twitter.

**Comment by DaleMcGrew** [comment] 2018-12-27 14:47
I have been unable to reproduce this error for Twitter. Closing.

**Closed by DaleMcGrew** 2018-12-27 14:47 UTC
Labels: Difficulty: High, Priority: 1
