### ISSUE TITLE
App Freezes Browser from Donate Page

### ISSUE THREAD

**Issue by pertrai1** [wevote/WebApp#834] opened 2017-05-13 14:14 UTC
### Please describe the issue (What happens? What do you expect?)

* Go to Donate
* Click on the User icon
* Expecting to see sign in option right away
* Does not show up so I try to click on WeVote
* Not able to do any user interactions until the event loop catches up to perform sign in dropdown

**Comment by DaleMcGrew** [comment] 2017-05-13 18:23
Thank you @pertrai1 for reporting this. I am not able to reproduce this. Can you share the browser and computer you were using? Do you have any tips of what might be happening from the console log? cc'ing @SailingSteve

**Comment by pertrai1** [comment] 2017-05-13 20:16
Yes it is Edge on Microsoft Surface. No issues that are showing in the console.

**Comment by SailingSteve** [comment] 2017-05-14 22:42
Hi,
    There is an "known" issue where maybe, if you donate without logging 
in or if Watchify refreshes the app while you are on the donation, you 
get an endless stream of retrieveVoter requests from the browser (~ 2 
per second), until the browser freezes up.  I think I saw it from the 
beginning of my working on the project, on Chrome.   I'll dig into it 
tomorrow.

Steve Podell

**Comment by pertrai1** [comment] 2017-05-14 23:08
@SailingSteve @DaleMcGrew This seems to be a edge case that happened yesterday while I was playing around with the app. Right now I am trying to reproduce in Edge on the Surface and I am not able to reproduce. I am going to go ahead and close.

**Comment by DaleMcGrew** [comment] 2017-05-14 23:20
Thank you Rob, but I think it is enough of an issue that we should fix it.  I appreciate you reporting it!

**Comment by SailingSteve** [comment] 2017-05-18 18:52
Not sure, but the endless loop of "/apis/v1/voterRetrieve/" calls with a bad voter_device_id seems to happen when you are transpiling with Watchify and BrowserSync updates the running JavaScript.

**Comment by SailingSteve** [comment] 2017-06-02 14:58
We were deleting cookies by setting "" for a payload, and -1 for a expiration.   But it was taking too long to take effect, putting us in a tight endless loop.  Changed over to cookies.js's cookies.removeItem("voter_device_id");  which appears to work instantly.  Solved the problem.

**Comment by SailingSteve** [comment] 2017-06-02 15:10
Fixed in pull request #878

**Comment by DaleMcGrew** [comment] 2017-06-02 15:11
Thank you @SailingSteve! I am marking this as Verify Fix so we can do some more testing before calling this closed.

**Comment by pertrai1** [comment] 2017-06-03 06:28
@SailingSteve - How does the one time donation fit in with this issue? Would be great if you could do a PR against this issue and separate donations into another PR if there is no relevance. If there is, great.

**Comment by DaleMcGrew** [comment] 2017-06-05 15:52
Hi @pertrai1, we checked in a fix for this issue (I merged code that fixes this, and pushed it to the live site.) Would you be willing to try to recreate the case where you saw this problem, and verify it is fixed?

**Comment by pertrai1** [comment] 2017-06-05 16:01
@DaleMcGrew 👍

**Closed** 2017-06-06 00:53 UTC
Labels: Bug
