### ISSUE TITLE
Footer shows up when keyboard is open - Cordova

### ISSUE THREAD

**Issue by LohitG** [wevote/WebApp#2382] opened 2019-06-24 17:27 UTC
The footer appears above the keyboard when the keyboard is opened. In Cordova, always turn off the Footer when the keyboard is open.
![IMG-7613](https://user-images.githubusercontent.com/23069689/60038934-6bc0ad80-966a-11e9-8aa4-c7fbc2b0109d.PNG)

**Comment by DaleMcGrew** [comment] 2019-06-27 04:49
Lohit checked in a potential fix for this in the file:
src/sass/components/_footer.scss
around line 53, but wasn't able to test it in Cordova.

**Comment by SailingSteve** [comment] 2019-06-27 20:19
@DaleMcGrew @LohitG  
For bugs like these, please list the devices that you reproduced the problem on.  I'm just guessing, but that looks like a small screen Android?  Is it an emulator, or an actual device?  If I wanted to see it exactly like you see it, what would the steps be?

**Comment by LohitG** [comment] 2019-06-27 22:53
@SailingSteve 
I found this bug of the iPhone SE and it would happen in every instance where the keyboard would be opened. An example would be the search bar on the Ballot page. Also I wasn't able to find this bug on Browserstack on the iPhone SE or any other devices. I can only see the error on my iPhone SE with the current We Vote app installed.

**Comment by DaleMcGrew** [comment] 2019-07-15 20:55
Verified by @ffrancetic

**Closed by DaleMcGrew** 2019-07-15 20:55 UTC
Labels: Cordova Specific, Difficulty: Medium, Priority: 1, Verify Fix
