### ISSUE TITLE
Close Modal "X": Make "click" area larger

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#1645] opened 2018-08-21 16:03 UTC
When you open a modal, the active hotspot for the "X" is too hard to hit. Please make the click area larger so it is easier to close the modal.
![img_5520](https://user-images.githubusercontent.com/7756031/44413757-028b7d80-a521-11e8-8c12-c4dc90f682af.jpeg)

**Comment by utsab** [comment] 2018-08-23 02:55
Hi @DaleMcGrew, question about this issue.  The problem is specifically on the mobile experience, correct?  Is that that you have to keep tapping on the screen until you finally hit the right spot, so you want the clickable area to be area to be larger for a better user experience? 

Also, can you assign this issue to me?  I'd be happy to take this on.

**Comment by DaleMcGrew** [comment] 2018-08-23 03:15
That is correct. You are welcome to take on this issue! Thank you @utsab.

**Closed** 2018-08-25 03:51 UTC
Labels: Difficulty: Easy, Priority: 2

**Comment by DaleMcGrew** [comment] 2018-08-25 04:07
Verified as fixed.
