### ISSUE TITLE
iPad Display: NavigatorInHeader spacing problem

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#512] opened 2016-09-29 19:00 UTC
### Please describe the issue (What happens? What do you expect?)
On an iPad (model 2), the NavigatorInHeader styles need some fine tuning.

Landscape Display:
![evernote camera roll 20160928 141130](https://cloud.githubusercontent.com/assets/7756031/18968023/35b450ac-863c-11e6-8ecc-6de7566ae4c5.png)

Portrait Display:
![evernote camera roll 20160928 141131](https://cloud.githubusercontent.com/assets/7756031/18968032/3dd41042-863c-11e6-99eb-d07fc61d9636.png)

**Comment by ixley** [comment] 2016-10-04 16:18
@DaleMcGrew I can't reproduce in Chrome's inspector. Can you provide more info about browser version and whether this behavior is consistent? [screenshot from Chrome inspector (iPad landscape: 1024 x 768)](https://cloud.githubusercontent.com/assets/160662/19082511/4dec3c0e-8a13-11e6-9758-62f8ec7af615.png)

One of the things we should do is establish a list of browsers that we intend to officially support. This will aid with testing and knowing what fallbacks we need to support.

**Comment by DaleMcGrew** [comment] 2016-10-04 16:26
Hi @ixley I don't see the problem in the Chrome simulator either. I am glad you created Issue #522 so we can figure out which devices we'll be supporting for now.

**Comment by pertrai1** [comment] 2016-10-04 22:59
If anything, might need to add a query for the `min-device-pixel-ratio: 1` for older iPad versions.

**Comment by ixley** [comment] 2016-10-24 05:20
Since I can't reproduce and this seems low priority, I'm closing this issue. Let's establish a [list of supported browsers](https://github.com/wevote/WebApp/issues/522) first so we know what our standards are.

**Closed by ixley** 2016-10-24 05:20 UTC
Labels: HTML / CSS, Priority 2
